# Court-ready .docx formatter using python-docx.
#
# Formatting conventions:
#   - Heading 1: matter type + parties
#   - Heading 2: jurisdiction line
#   - Body: draft paragraphs (double-spaced, justified)
#   - Footnotes: grounded citations with source chunk reference
#
# The output follows Indian High Court / Supreme Court filing conventions
# for formatted petitions — no unusual fonts, standard Times New Roman 12pt.

from __future__ import annotations

import os
import re

from docx import Document  # type: ignore[import]
from docx.enum.text import WD_ALIGN_PARAGRAPH  # type: ignore[import]
from docx.shared import Inches, Pt  # type: ignore[import]

from lexagent.state import LexState


def write_docx(state: LexState, output_path: str) -> str:
    """
    Write state["draft_output"] to a court-ready .docx file.
    Returns the resolved absolute path of the written file.
    """
    doc = Document()

    # ----------------------------------------------------------------
    # Page margins — standard Indian court filing: 1.5" left, 1" others
    # ----------------------------------------------------------------
    for section in doc.sections:
        section.left_margin = Inches(1.5)
        section.right_margin = Inches(1.0)
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)

    # ----------------------------------------------------------------
    # Title block
    # ----------------------------------------------------------------
    matter_type = (state.get("matter_type") or "Legal Document").title()
    parties = state.get("parties") or {}
    plaintiff = parties.get("plaintiff") or parties.get("petitioner") or "Petitioner"
    defendant = parties.get("defendant") or parties.get("respondent") or "Respondent"
    jurisdiction = state.get("jurisdiction") or ""

    title_para = doc.add_heading(matter_type, level=1)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    parties_para = doc.add_heading(f"{plaintiff}  v.  {defendant}", level=2)
    parties_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    if jurisdiction:
        jur_para = doc.add_paragraph(jurisdiction)
        jur_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        _set_font(jur_para, italic=True)

    doc.add_paragraph()  # spacer

    # ----------------------------------------------------------------
    # Draft body — split on double newlines into paragraphs
    # ----------------------------------------------------------------
    draft = state.get("draft_output") or ""
    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", draft) if p.strip()]

    grounded = state.get("grounded_citations") or []
    # Build a lookup: citation string → chunk_id for footnote text
    cite_to_chunk: dict[str, str] = {
        g["source"]: (g["chunk_id"] or "unverified")
        for g in grounded
    }

    for para_text in paragraphs:
        p = doc.add_paragraph(para_text)
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        _set_font(p)
        _set_paragraph_spacing(p)

    # ----------------------------------------------------------------
    # Citations appendix — grounded citations as a numbered list
    # WHY: python-docx does not support true footnotes without low-level
    # XML manipulation. An appendix is court-acceptable for typed petitions.
    # ----------------------------------------------------------------
    if grounded:
        doc.add_page_break()
        doc.add_heading("Citations", level=2)
        for i, g in enumerate(grounded, start=1):
            status = "✓ Grounded" if g["verified"] else "⚠ Unverified"
            chunk_ref = g["chunk_id"] or "—"
            line = f"{i}. {g['source']}  [{status}]  (chunk: {chunk_ref})"
            p = doc.add_paragraph(line)
            _set_font(p, size=10)

    # ----------------------------------------------------------------
    # Matter metadata footer
    # ----------------------------------------------------------------
    doc.add_paragraph()
    meta = (
        f"Matter ID: {state.get('matter_id') or '—'}  |  "
        f"Generated by LexAgent  |  "
        f"Phase 5 draft — verify citations before filing"
    )
    meta_p = doc.add_paragraph(meta)
    meta_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_font(meta_p, size=9, italic=True)

    # ----------------------------------------------------------------
    # Save
    # ----------------------------------------------------------------
    abs_path = os.path.abspath(output_path)
    doc.save(abs_path)
    return abs_path


# -----------------------------------------------------------------------
# Formatting helpers
# -----------------------------------------------------------------------


def _set_font(
    para,
    size: int = 12,
    bold: bool = False,
    italic: bool = False,
) -> None:
    """Apply font settings to every run in a paragraph."""
    for run in para.runs:
        run.font.name = "Times New Roman"
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.italic = italic


def _set_paragraph_spacing(para) -> None:
    """Double-space body paragraphs with 12pt spacing after."""
    fmt = para.paragraph_format
    fmt.space_after = Pt(12)
    fmt.line_spacing = Pt(24)  # ~double spacing for 12pt font
