# Review node: validation gate that runs after cite, before .docx output.
#
# Checks (in order of severity):
#   P0 — Blocking: lawyer note leakage, empty draft, incorrect party labels
#   P1 — Structural: missing required sections (cause of action, jurisdiction, limitation, prayer)
#   P2 — Quality: draft length, unverified citations
#
# P0 issues block output (set error, do not write .docx).
# P1/P2 issues annotate but do not block.

from rich.console import Console

from lexagent.state import LexState

console = Console()

# WHY: Rough word-count limits by document type.
_WORD_LIMITS: dict[str, int] = {
    "injunction": 5000,
    "writ petition": 8000,
    "legal notice": 2000,
    "plaint": 10000,
    "written statement": 10000,
    "affidavit": 3000,
    "vakalatnama": 500,
    "s138_complaint": 4000,
    "cheque dishonour": 4000,
}
_DEFAULT_WORD_LIMIT = 12000

# ---------------------------------------------------------------------------
# Structural section requirements — keyed by matter_type (lowercase, underscore)
# Each entry: list of (keyword, severity) where severity is "P0" or "P1"
# P0 → blocks filing; P1 → warns only
# ---------------------------------------------------------------------------
_REQUIRED_SECTIONS: dict[str, list[tuple[str, str]]] = {
    "s138_complaint": [
        ("cause of action",  "P0"),
        ("jurisdiction",     "P0"),
        ("limitation",       "P0"),
        ("prayer",           "P0"),
        ("verification",     "P1"),
        ("section 138",      "P0"),
    ],
    "writ_petition": [
        ("grounds",          "P0"),
        ("prayer",           "P0"),
        ("verification",     "P1"),
        ("cause of action",  "P0"),
        ("jurisdiction",     "P1"),
    ],
    "plaint": [
        ("cause of action",  "P0"),
        ("jurisdiction",     "P0"),
        ("limitation",       "P0"),
        ("prayer",           "P0"),
        ("verification",     "P1"),
        ("valuation",        "P1"),
    ],
    "written_statement": [
        ("preliminary objection", "P0"),
        ("prayer",               "P0"),
        ("verification",         "P1"),
    ],
    "bail_application": [
        ("prayer",           "P0"),
        ("grounds",          "P0"),
    ],
    "injunction_application": [
        ("prima facie",      "P0"),
        ("balance of convenience", "P0"),
        ("irreparable",      "P0"),
        ("prayer",           "P0"),
    ],
}

# Phrases that indicate lawyer working notes leaked into the filing body.
# WHY: base_system.md appends these after '---'. If they appear BEFORE the
# separator (or if the separator was missed), the filing is contaminated.
_LAWYER_NOTE_LEAKAGE_PATTERNS = [
    "⚠ high risk",
    "⚡ medium risk",
    "ℹ low risk",
    "high risk",
    "medium risk",
    "low risk — ",
    "generated by lexagent",
    "phase 5 draft",
    "matter id:",
    "plain english summary",
    "risk assessment",
]


def _word_count(text: str) -> int:
    return len(text.split())


def _jurisdiction_limit(matter_type: str | None) -> int:
    if not matter_type:
        return _DEFAULT_WORD_LIMIT
    key = (matter_type or "").lower().strip()
    for known, limit in _WORD_LIMITS.items():
        if known in key:
            return limit
    return _DEFAULT_WORD_LIMIT


def _normalise_matter_type(matter_type: str | None) -> str:
    """Normalise to the key used in _REQUIRED_SECTIONS."""
    if not matter_type:
        return ""
    return matter_type.lower().strip().replace(" ", "_")


def _check_lawyer_note_leakage(filing_body: str) -> list[str]:
    """
    Scan the filing body for phrases that indicate lawyer notes were not stripped.
    Returns a list of matched phrases.
    """
    lower = filing_body.lower()
    found = []
    for pattern in _LAWYER_NOTE_LEAKAGE_PATTERNS:
        if pattern.lower() in lower:
            found.append(pattern)
    return found


def _check_required_sections(
    filing_body: str, matter_type_key: str
) -> tuple[list[str], list[str]]:
    """
    Check that required section keywords appear in the filing body.

    Returns:
        (p0_missing, p1_missing) — lists of section names that are absent.
    """
    if matter_type_key not in _REQUIRED_SECTIONS:
        return [], []

    lower = filing_body.lower()
    p0_missing: list[str] = []
    p1_missing: list[str] = []

    for keyword, severity in _REQUIRED_SECTIONS[matter_type_key]:
        if keyword.lower() not in lower:
            if severity == "P0":
                p0_missing.append(keyword)
            else:
                p1_missing.append(keyword)

    return p0_missing, p1_missing


def _check_placeholder_leakage(filing_body: str) -> list[str]:
    """Find unfilled placeholder patterns like [INSERT ...] or [___]."""
    import re
    patterns = re.findall(r"\[(?:INSERT|FILL|ADD|___|\.\.\.).*?\]", filing_body, re.IGNORECASE)
    return patterns


async def run(state: LexState) -> dict:
    try:
        from lexagent.tools.docx_writer import _split_draft  # local import to avoid circularity

        draft = state.get("draft_output") or ""
        # Use only the filing body (before '---') for structural checks
        filing_body, _ = _split_draft(draft)

        unverified = state.get("unverified_citations") or []
        grounded = state.get("grounded_citations") or []
        matter_type = state.get("matter_type")
        matter_type_key = _normalise_matter_type(matter_type)
        docx_output_path: str | None = state.get("docx_path")

        p0_issues: list[str] = []
        p1_issues: list[str] = []
        risk_annotations: list[dict] = []

        # ── P0: empty draft ──────────────────────────────────────────────────
        if not filing_body.strip():
            p0_issues.append("Draft output is empty")

        # ── P0: lawyer note leakage in filing body ───────────────────────────
        leaked = _check_lawyer_note_leakage(filing_body)
        if leaked:
            p0_issues.append(
                f"Lawyer working notes leaked into filing body: {', '.join(leaked[:3])}"
            )

        # ── P0/P1: required structural sections ──────────────────────────────
        p0_missing, p1_missing = _check_required_sections(filing_body, matter_type_key)
        if p0_missing:
            p0_issues.append(
                f"Missing required sections (P0): {', '.join(p0_missing)}"
            )
        if p1_missing:
            p1_issues.append(
                f"Missing recommended sections: {', '.join(p1_missing)}"
            )

        # ── P1: placeholder leakage ──────────────────────────────────────────
        placeholders = _check_placeholder_leakage(filing_body)
        if placeholders:
            p1_issues.append(
                f"Unfilled placeholders in filing body: {', '.join(placeholders[:5])}"
            )

        # ── P2: unverified citations ─────────────────────────────────────────
        if unverified:
            p1_issues.append(
                f"{len(unverified)} citation(s) could not be grounded: "
                + ", ".join(unverified[:3])
                + (" ..." if len(unverified) > 3 else "")
            )

        # ── P2: draft length ─────────────────────────────────────────────────
        limit = _jurisdiction_limit(matter_type)
        wc = _word_count(draft)
        if wc > limit:
            p1_issues.append(
                f"Draft is {wc} words — exceeds {matter_type or 'document'} "
                f"guidance of {limit} words"
            )

        # ── Report ───────────────────────────────────────────────────────────
        if p0_issues:
            for issue in p0_issues:
                console.print(f"[bold red]✗ P0 Review:[/bold red] {issue}")
            for issue in p1_issues:
                console.print(f"[yellow]⚠ P1 Review:[/yellow] {issue}")
            # P0 issues block .docx output — return error so CLI can re-draft
            return {
                "error": f"P0 review failures (filing blocked): {'; '.join(p0_issues)}",
                "risk_annotations": [
                    {"clause": "review", "risk_level": "H", "note": i} for i in p0_issues
                ] + [
                    {"clause": "review", "risk_level": "M", "note": i} for i in p1_issues
                ],
            }

        for issue in p1_issues:
            console.print(f"[yellow]⚠ P1 Review:[/yellow] {issue}")

        if not p0_issues and not p1_issues:
            console.print("[green]✓ Review:[/green] All structural checks passed")
        else:
            console.print("[green]✓ Review:[/green] Structural checks passed (warnings above)")

        # ── Generate .docx (only reaches here if no P0 blocking issues) ──────
        # WHY run_in_executor: write_docx does synchronous disk I/O (python-docx).
        # Running it in the default ThreadPoolExecutor keeps the asyncio event loop
        # unblocked — critical for serving concurrent Telegram users.
        docx_path_out: str | None = None
        if docx_output_path and filing_body.strip():
            import asyncio
            from lexagent.tools.docx_writer import write_docx
            loop = asyncio.get_event_loop()
            docx_path_out = await loop.run_in_executor(None, write_docx, state, docx_output_path)
            console.print(f"[bold green]✓ Draft saved to:[/bold green] {docx_path_out}")

        return {
            "docx_path": docx_path_out,
            "risk_annotations": [
                {"clause": "review", "risk_level": "M", "note": i} for i in p1_issues
            ] if p1_issues else None,
        }

    except Exception as e:
        return {"error": str(e)}
